# Numpy学习  
***
NumPy 是一个运行速度非常快的数学库，主要用于数组计算，包含：
   - 一个强大的N维数组对象 ndarray
   - 广播功能函数
   - 整合 C/C++/Fortran 代码的工具
   - 线性代数、傅里叶变换、随机数生成等功能    
   
**Numpy官网**：<http://www.numpy.org/>  
**Numpy源代码**：<https://github.com/numpy/numpy>  
**Numpy教程**：<http://www.runoob.com/numpy/numpy-tutorial.html>

## 安装  
*******
**我的安装环境**：Win10 64bit + Python3.7.1  
Numpy的安装比较简单，在命令行直接敲入命令：<font color=#FF0000>   **pip install numpy** </font>   
安装完成后可以使用命令 <font color=#FF0000> **pip show numpy** </font> 查看Numpy支持包的信息。 

## Numpy Ndarray对象
***
ndarray 对象是用于存放同类型元素的多维数组，以 0 下标为开始进行集合中元素的索引。  
创建一个 ndarray 直接调用 .array 函数即可：  
<font color=#FF0000> **array = numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)** </font> 

object|dtype|copy|order|subok|ndmin
:--:|:--:|:--:|:--:|:--:|:--:
数组或嵌套的数列|数组元素的数据类型，可选|对象是否需要复制，可选|创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）|默认返回一个与基类类型一致的数组|	指定生成数组的最小维度  


In [53]:
import numpy as np

# -------------- Numpy创建对象 -------------- #
zeros_array = np.zeros((3,4),dtype = np.int16)
print('元素全为‘0’的3 * 4零矩阵:\n',zeros_array)

ones_array = np.ones((4,3),dtype = np.int16)
print('\n元素全为‘1’的4 * 4矩阵:\n', ones_array)

complex_array = np.array([1,  2,  3], dtype = complex) 
print('\n复数矩阵:\n', complex_array)

range_array = np.arange(1,20,2).reshape(2,5)
print('\narange生成的矩阵:\n', range_array)
# a = np.arange(1,11).reshape(5,2)
#print(a)

# numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
linspace_array = np.linspace(1,20,8).reshape(2,4)
print('\nlinspace生成的矩阵:\n', range_array)

# numpy.logspace 函数用于创建一个于等比数列。
# np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
log_array = np.logspace(1.0, 10.0, num = 10, base = 2).reshape(2,5)
print('\nlogspace生成的矩阵:\n', log_array)

empty_array = np.empty((3,2),dtype = float)
print('\nempty生成的矩阵:\n', empty_array)

# 从已有数组创建新的数组 使用 
# np.asarray(a, dtype = None, order = None)
# a -- 任意形式的输入参数，  可以是列表, 
#      列表的元组, 元组, 元组的元组, 元
#      组的列表，多维数组。
as_array = np.asarray(empty_array, dtype = int).reshape(2,3)
print('\nasarray生成的矩阵:\n', as_array)

# numpy.frombuffer 用于实现动态数组。
# numpy.frombuffer 接受 buffer 输入
# 参数，以流的形式读入转化成 
# ndarray 对象。
string =  b'Truth is the daughter of time' # 字节只能存储ASCII文字字符
#print(type(string))
frombuffer = np.frombuffer(string, dtype =  'S1')  
print('\nfrombuffer生成的矩阵:\n', frombuffer)

# numpy.fromiter从可迭代对象中建立 ndarray 对象，返回一维数组。  
range_list = range(20)
it = iter(range_list)
 # 使用迭代器创建 ndarray 
it_object = np.fromiter(it, dtype = int).reshape([4,5])
print('\nfromiter生成的矩阵:\n', it_object)

# -------------- Numpy切片和索引 -------------- #
# 利用内建函数 slice 切片
s = slice(4,0,-1)
print('\n原数据为:',range_array[1])
print('使用 slice 切片:',range_array[1][s])
# 利用冒号 ":" 切片
print('使用 ":" 切片:',range_array[1][1:4])
# 除此之外，还有一些其他的索引方式，可以参考：
# http://www.runoob.com/numpy/numpy-advanced-indexing.html

元素全为‘0’的3 * 4零矩阵:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

元素全为‘1’的4 * 4矩阵:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

复数矩阵:
 [1.+0.j 2.+0.j 3.+0.j]

arange生成的矩阵:
 [[ 1  3  5  7  9]
 [11 13 15 17 19]]

linspace生成的矩阵:
 [[ 1  3  5  7  9]
 [11 13 15 17 19]]

logspace生成的矩阵:
 [[   2.    4.    8.   16.   32.]
 [  64.  128.  256.  512. 1024.]]

empty生成的矩阵:
 [[1. 0.]
 [2. 0.]
 [3. 0.]]

asarray生成的矩阵:
 [[1 0 2]
 [0 3 0]]

frombuffer生成的矩阵:
 [b'T' b'r' b'u' b't' b'h' b' ' b'i' b's' b' ' b't' b'h' b'e' b' ' b'd'
 b'a' b'u' b'g' b'h' b't' b'e' b'r' b' ' b'o' b'f' b' ' b't' b'i' b'm'
 b'e']

fromiter生成的矩阵:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

原数据为: [11 13 15 17 19]
使用 slice 切片: [19 17 15 13]
使用 ":" 切片: [13 15 17]


## Numpy 数据类型
***
**Numpy数据类型讲解**：<http://www.runoob.com/numpy/numpy-dtype.html>  
除了常见的布尔型、整型、浮点型，还包括复数类型，除此之外，可以利用 **dtype** 建立结构化数据类型。

In [22]:
# -------------- 自定义结构化数据类型 -------------- #
employee = np.dtype([('name', 'a20'), ('age', 'i1'), ('salary', 'f4')]) 

emp = np.array([('Alex', 21, 1500),('John', 18, 1200)], dtype = employee) 

print(emp)

print('emp 数据类型为:' , emp.dtype)

[(b'Alex', 21, 1500.) (b'John', 18, 1200.)]
emp 数据类型为: [('name', 'S20'), ('age', 'i1'), ('salary', '<f4')]


## Numpy 属性
***
Numpy数组的一些基本属性在下面的例子中给出。

In [58]:
# -------------- numpy 属性 -------------- #
array = np.array([[1,2,3],[4,5,6]])
 
print('矩阵:', array)

print('元素类型:', array.dtype)

print('矩阵维数:', array.ndim)

print('矩阵维度（n 行 m 列）:', array.shape)

print('矩阵元素总个数:', array.size)

print('每个元素的大小: %d 字节;' % array.itemsize)

print('元素的实部:', array.real)

print('元素的虚部：', array.imag)

print('实际数组元素的缓冲区:', array.data)

print('内存信息:', array.flags)

矩阵: [[1 2 3]
 [4 5 6]]
元素类型: int32
矩阵维数: 2
矩阵维度（n 行 m 列）: (2, 3)
矩阵元素总个数: 6
每个元素的大小: 4 字节;
元素的实部: [[1 2 3]
 [4 5 6]]
元素的虚部： [[0 0 0]
 [0 0 0]]
实际数组元素的缓冲区: <memory at 0x000001B4AA2E68B8>
内存信息:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


# Numpy 广播（Broadcast）
***
针对不同形状的数组，Numpy使用了广播（Broadcast）来进行计算，使数组对应位置的元素能进行算术运算。

In [7]:
# -------------- numpy 广播 -------------- #
a = np.arange(1,13,1).reshape(3,4)
print('array "a" is:\n',a)

b = np.array([1,2,3,4])
print('array "b" is:\n',b)

c = a + b
print('array "c" is:\n',c)

array "a" is:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
array "b" is:
 [1 2 3 4]
array "c" is:
 [[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


# Numpy 数组操作
***
Numpy 可以对数组进行多种操作，包括以下几类：  
 - 修改数组形状   
 
函数|描述
--:|--:  
reshape|不改变数据的条件下修改形状  
flat|数组元素迭代器  
flatten|返回一份数组拷贝，对拷贝所做的修改不会影响原始数组  
ravel|返回展开数组  
   
 - 翻转数组
 
 
函数|描述
--:|--:
transpose|对换数组的维度
ndarray.T|和 self.transpose() 相同
rollaxis|向后滚动指定的轴
swapaxes|对换数组的两个轴
 
 - 修改数组维度
 
 
维度|描述
--:|--:
broadcast|产生模仿广播的对象
broadcast_to|将数组广播到新形状
expand_dims|扩展数组的形状
squeeze|从数组的形状中删除一维条目
 
 - 连接数组          
     
函数|描述
--:|--:
concatenate|连接沿现有轴的数组序列
stack|沿着新的轴加入一系列数组。
hstack|水平堆叠序列中的数组（列方向）
vstack|竖直堆叠序列中的数组（行方向）

 - 分割数组
 
 
函数|数组及操作
--:|--:
 split|将一个数组分割为多个子数组
hsplit|将一个数组水平分割为多个子数组（按列）
vsplit|将一个数组垂直分割为多个子数组（按行）
 
 - 数组元素的添加与删除
 
 
函数|元素及描述
--:|--:
resize|返回指定形状的新数组
append|将值添加到数组末尾
insert|沿指定轴将值插入到指定下标之前
delete|删掉某个轴的子数组，并返回删除后的新数组
unique|查找数组内的唯一元素


# Numpy “copy” 和 “deep copy”
***
简而言之，“copy”是简单的复制，复制对象和被复制对象共享同一内存空间，任一元素改变，则两者都会改变。“deep copy”(np.copy())则会开辟新的内存空间，复制对象与被复制对象被完全分开，改变其中一个，并不会影响另一个。

In [17]:
x = np.arange(1,5,1)
y = x
z = x.copy()  # deep copy
print('"x" is:',x)
print('"y" is:',y)
print('"z" is:',z)

print('"y" is "x":',y is x)
print('"z" is "x":',z is x)

x[0] = 5

print('"x" is:',x)
print('"y" is:',y)
print('"z" is:',z)

"x" is: [1 2 3 4]
"y" is: [1 2 3 4]
"z" is: [1 2 3 4]
"y" is "x": True
"z" is "x": False
"x" is: [5 2 3 4]
"y" is: [5 2 3 4]
"z" is: [1 2 3 4]


内容尚有不足和不完整的地方，参考Numpy官方网站 <https://docs.scipy.org/doc/numpy/user/quickstart.html>